- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  vars_files:
    - haproxy/files/main.yaml

  tasks:
    - name: Install haproxy repos
      community.kubernetes.helm_repository:
        name: haproxy
        repo_url: "https://haproxytech.github.io/helm-charts"
      delegate_to: localhost

    - name: Copy global chart
      copy:
        src: haproxy/files/global
        dest: /tmp/
      delegate_to: localhost

    #
    - name: Copy ca cert
      copy:
        src: haproxy/files/ca.crt
        dest: /tmp/
      delegate_to: localhost

    #
    - name: Copy voight.org cert
      copy:
        src: haproxy/files/voight.org.crt
        dest: /tmp/
      delegate_to: localhost


    - name: Update helm repos
      command: helm repo update
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: haproxy/files/haproxy-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Add Voight.org Certificates
      command: >
        helm upgrade -i certificates /tmp/global
        --set-file tls.crt=/tmp/voight.org.crt
        --set tls.key='{{ voightorgkey }}'
        --set-file ca.crt=/tmp/ca.crt
      delegate_to: localhost

    - name: Apply haproxy chart
      command: helm install haproxy haproxy/kubernetes-ingress -f files/haproxy-values.yaml
      delegate_to: localhost
