apiVersion: v1
kind: Secret
metadata:
  name: site-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: site-ca
#type: kubernetes.io/tls
#data:
#  ca.crt: {{ .Values.ca.crt | b64enc }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: Secret
metadata:
  name: site-cert
  namespace: devops
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
